services:
  app:
    image: apx-coffee
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    networks:
      - backend
    depends_on:
      mongo:
        condition: service_started

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - dbdata:/data/db
    networks:
      - backend

volumes:
  dbdata:

networks:
  backend:
